export const API_BASE_URL =
  process.env.API_BASE_URL || "http://localhost:9001/api";

// "https://api.pilox.com/api";
export const API_ROUTES = {
  NEWSLETTER_SUBSCRIBE: "/auth/newsletter-subscribe",
  SIGNUP: "/auth/signup",
  LOGIN: "/auth/login",
  FORGOT_PASSWORD: "/auth/forgot-password",
  RESET_PASSWORD: "/auth/reset-password",
  RESEND_VERIFICATION_EMAIL: "/auth/resend-verification-email",
  VERIFY_EMAIL: "/auth/verify-email",
  GOOGLE_AUTH: "/auth/google-auth",
  CHAT_WITH_VIDEO: "/youtube/chat-with-video",
  YOUTUBE_VIDEO_PROGRESS: "/youtube/get-progress",
  USER_DETAILS: "/user/details",
  UPDATE_DETAILS: "/user/update-details",
  UPDATE_PASSWORD: "/user/update-password",
  REFERRAL_DETAILS: "/user/referral-details",
  REFERRAL_HISTORY: "/user/referral-history",
  YOUTUBE_CHAT_HISTORY: "/youtube/all-chat-history",
  YOUTUBE_CHAT_HISTORY_BY_ID: "/youtube/chat-history",
  INCREASE_CHAT_LIMIT: "/youtube/increase-chat-limit",
  DELETE_CHAT: "/youtube/delete-chat-history",
  GENERATE_PDF: "/pdf/generate",
  ANALYTICS_QUERY: "/analytics/query",
  CHAT_HISTORY: "/chat/history",
  CHAT_HISTORIES: "/chat/histories",
  ANALYZE_PDF: "/pdf/analyze",
  ANALYSIS_STATUS: "/pdf/analysis-status",
  GET_CHAT_MESSAGES: "/chat/messages",
  GENERATE_VIDEO: "/pdf/generate-video",
  CREDIT_HISTORY: "/user/credit-history",
  GENERATE_QUIZ: "/pdf/generate-quiz",
  GENERATE_MCQ: "/pdf/generate-true-false",
  VERIFY_THEORY_ANSWER: "/pdf/verify-theory-answer",
  GENERATE_THEORY: "/pdf/generate-theory",
  GENERATE_FLASHCARDS: "/pdf/generate-flashcards",
  VIDEO_STATUS: "/pdf/video-status",
  DOWNLOAD_VIDEO: "/pdf/download-video",
  VIDEO_PROGRESS: "/pdf/video-progress",
  VIDEO_PREVIEW: "/pdf/preview-video",
  MORE_VIDEOS: "/pdf/more-videos",
  SUBMIT_FEEDBACK: "/feedback/submit",
  FEEDBACK_HISTORY: "/feedback/history",
  FEEDBACK_DATA: "/feedback/data",
} as const;
